apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  namespace: sirine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: almadsam/node-server:latest
        env:
        - name: RABBITMQ_HOST
          value: "production-rabbitmqcluster.<votre-nom>.svc.cluster.local"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: POSTGRES_HOST
          value: "postgres.<votre-nom>.svc.cluster.local"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "mydatabase"
        ports:
        - containerPort: 4040
---
apiVersion: v1
kind: Service
metadata:
  name: node-server
  namespace: sirine
spec:
  ports:
  - port: 4040
  selector:
    app: node-server